version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nyktra_se
    ports:
      - "8888:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
